language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - echo "Skipping test..."
deploy:
  provider: npm
  email: "zonayedpca@yahoo.com"
  api_key: $npm_token
  skip_cleanup: true
  on:
    branch: master
